# Generated by Django 4.0.5 on 2022-06-23 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.author', verbose_name='Author'),
        ),
    ]
