# Generated by Django 4.0.5 on 2022-06-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='release_data',
            field=models.DateField(verbose_name='Release Data'),
        ),
    ]
